project:
  type: website
  output-dir: docs

website:
  title: "Classifying Age Groups with Health Data: A Step Toward Smarter Public Health Programs"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



