<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Forgive Agbesi">
<meta name="dcterms.date" content="2025-01-15">

<title>Classifying Age Groups with Health Data: A Step Toward Smarter Public Health Programs</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-listing/list.min.js"></script>
<script src="site_libs/quarto-listing/quarto-listing.js"></script>
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>

  window.document.addEventListener("DOMContentLoaded", function (_event) {
    const listingTargetEl = window.document.querySelector('#listing-listing .list');
    if (!listingTargetEl) {
      // No listing discovered, do not attach.
      return; 
    }

    const options = {
      valueNames: ['listing-date','listing-title','listing-author','listing-image','listing-description','listing-categories',{ data: ['index'] },{ data: ['categories'] },{ data: ['listing-date-sort'] },{ data: ['listing-file-modified-sort'] }],
      
      searchColumns: ["listing-date","listing-title","listing-author","listing-image","listing-description","listing-categories"],
    };

    window['quarto-listings'] = window['quarto-listings'] || {};
    window['quarto-listings']['listing-listing'] = new List('listing-listing', options);

    if (window['quarto-listing-loaded']) {
      window['quarto-listing-loaded']();
    }
  });

  window.addEventListener('hashchange',() => {
    if (window['quarto-listing-loaded']) {
      window['quarto-listing-loaded']();
    }
  })
  </script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Classifying Age Groups with Health Data: A Step Toward Smarter Public Health Programs</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-page-left">
      <h1 class="title">Classifying Age Groups with Health Data: A Step Toward Smarter Public Health Programs</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta column-page-left">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Forgive Agbesi </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">January 15, 2025</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        
    <h5 class="quarto-listing-category-title">Categories</h5><div class="quarto-listing-category category-default"><div class="category" data-category="">All <span class="quarto-category-count">(2)</span></div><div class="category" data-category="analysis">analysis <span class="quarto-category-count">(1)</span></div><div class="category" data-category="code">code <span class="quarto-category-count">(1)</span></div><div class="category" data-category="news">news <span class="quarto-category-count">(2)</span></div></div></div>
<!-- main -->
<main class="content quarto-banner-title-block column-page-left" id="quarto-document-content">





<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>This blog delves into the use of machine learning classification models specifically Logistic Regression, to predict age groups (adults versus seniors) based on health data. By applying Logistic Regression, we explored how these models can be leveraged to understand age-related health patterns, an essential task for designing more targeted public health interventions. Although the model showed initial promise, its effectiveness was limited by class imbalance, with most predictions falling into the adult category. We also explored solutions such as class weighting to improve balance and refine predictions. Despite this, the model’s accuracy for predicting seniors remained low in terms of precision and recall, indicating there is still room for improvement. Optimizing hyperparameters and focusing on metrics like precision and recall rather than overall accuracy could yield better results. Ultimately, this analysis demonstrates the potential of machine learning to inform public health strategies, providing actionable insights for more personalized and effective care for aging populations.</p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>As we grow older, our health needs evolve in ways that profoundly impact our quality of life. Imagine if we could leverage data to predict these changes, leading to more personalized and effective public health programs. This analysis explores whether health data can distinguish between adults (under 65) and seniors (65+), offering insights into how we might improve public health initiatives for aging populations.</p>
<p>The dataset used to answer this question is the National Health and Nutrition Survey 2013-2014 (NHANES) Age Prediction Subset (<span class="citation" data-cites="NHANES2019">NHANES (<a href="#ref-NHANES2019" role="doc-biblioref">2019</a>)</span>). It was originally prepared for a research paper on predicting diabetes and cardiovascular disease in patients (<span class="citation" data-cites="DinhMiertschin2016">Dinh and Miertschin (<a href="#ref-DinhMiertschin2016" role="doc-biblioref">2016</a>)</span> and <span class="citation" data-cites="MukhtarAzwari2021">Mukhtar and Al Azwari (<a href="#ref-MukhtarAzwari2021" role="doc-biblioref">2021</a>)</span>). The dataset’s stated purpose was to assess the health and nutritional status of adults and children in the United States (<span class="citation" data-cites="Papazafiropoulou2024">Papazafiropoulou (<a href="#ref-Papazafiropoulou2024" role="doc-biblioref">2024</a>)</span>), however respondents were classified as either Adults (respondents under 65 years of age) or Seniors (respondents 65 years of age or older). Respondents were located in the United States and provided data through interviews, physical examinations, and laboratory tests to the National Center for Health Statistics (NCHS) (part of the Centers for Disease Control and Prevention (CDC)). While the dataset has been used in previous research on diabetes and cardiovascular disease, this analysis focuses specifically on age prediction. By examining patterns in health data, we aim to evaluate the feasibility of machine learning models for classifying age groups and identify potential avenues for improving public health strategies.</p>
<p>This analysis focuses on predictive modeling, addressing challenges such as class imbalance and model performance metrics like precision and recall. While we concentrate on age classification, exploring the factors most predictive of age lies outside the scope of this study. By narrowing our focus, we aim to provide actionable insights that inform future work in age-related health analytics.</p>
</section>
<section id="methods-results" class="level2">
<h2 class="anchored" data-anchor-id="methods-results">Methods &amp; Results</h2>
<section id="data-sources" class="level3">
<h3 class="anchored" data-anchor-id="data-sources">Data Sources</h3>
<p>This dataset was sourced from the [NHANES], a large-scale public health initiative that collects health and nutritional data from a representative sample of adults and seniors in the U.S. Data were collected through a combination of clinical measurements and self-reported surveys between [years]. The dataset contains information on demographic, physical activity, and metabolic health factors.</p>
</section>
<section id="conducting-eda-on-the-training-set" class="level3">
<h3 class="anchored" data-anchor-id="conducting-eda-on-the-training-set">Conducting EDA on the training set</h3>
<div class="cell" data-execution_count="3">
<div id="tbl-summary-stats" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="3">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-summary-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Summary Statistics
</figcaption>
<div aria-describedby="tbl-summary-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="3">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 20%">
<col style="width: 8%">
<col style="width: 16%">
<col style="width: 11%">
<col style="width: 8%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">gender</th>
<th style="text-align: right;">physical_activity</th>
<th style="text-align: right;">bmi</th>
<th style="text-align: right;">blood_glucose</th>
<th style="text-align: right;">diabetic</th>
<th style="text-align: right;">oral</th>
<th style="text-align: right;">blood_insulin</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">count</td>
<td style="text-align: right;">1775</td>
<td style="text-align: right;">1775</td>
<td style="text-align: right;">1775</td>
<td style="text-align: right;">1775</td>
<td style="text-align: right;">1775</td>
<td style="text-align: right;">1775</td>
<td style="text-align: right;">1775</td>
</tr>
<tr class="even">
<td style="text-align: left;">mean</td>
<td style="text-align: right;">1.51</td>
<td style="text-align: right;">1.82</td>
<td style="text-align: right;">27.78</td>
<td style="text-align: right;">99.11</td>
<td style="text-align: right;">1.99</td>
<td style="text-align: right;">113.89</td>
<td style="text-align: right;">11.66</td>
</tr>
<tr class="odd">
<td style="text-align: left;">std</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.38</td>
<td style="text-align: right;">7.15</td>
<td style="text-align: right;">17.08</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">45.79</td>
<td style="text-align: right;">9.54</td>
</tr>
<tr class="even">
<td style="text-align: left;">min</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">14.5</td>
<td style="text-align: right;">63</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">1.02</td>
</tr>
<tr class="odd">
<td style="text-align: left;">25%</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">22.7</td>
<td style="text-align: right;">91</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">87</td>
<td style="text-align: right;">5.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">50%</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">26.7</td>
<td style="text-align: right;">97</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">104</td>
<td style="text-align: right;">8.89</td>
</tr>
<tr class="odd">
<td style="text-align: left;">75%</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">31.1</td>
<td style="text-align: right;">103</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">129</td>
<td style="text-align: right;">14.26</td>
</tr>
<tr class="even">
<td style="text-align: left;">max</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">70.1</td>
<td style="text-align: right;">405</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">604</td>
<td style="text-align: right;">102.29</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The training data has 1775 observations. Since gender, physical_activity, and diabetic features were categorical, only the mean and standard deviation from the table above were relevant for those columns. Body mass index values below 18 are considered underweight, and values over 40 are considered severely obese. We observed that the middle 50% of values fall between 22.7 &amp; 31.1, though the max was 70.1, which is concerningly high. Blood glucose, oral, and blood insulin have their own ranges, so it was necessary to standardize these variables before fitting our model.</p>
</section>
<section id="visualization-for-eda" class="level3">
<h3 class="anchored" data-anchor-id="visualization-for-eda">Visualization for EDA</h3>
<p>The distributions in <a href="#fig-feat-distributions" class="quarto-xref">Figure&nbsp;1</a> below show class imbalance, with very few seniors relative to adults in our dataset. Across numeric variables, mode values for seniors were less pronounced than they were for adults, though ranges seemed similar. Seniors seemed to have higher oral values and lower blood insulin values than adults.</p>
<div id="fig-feat-distributions" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-feat-distributions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../results/figures/eda_histogram.png" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-feat-distributions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Feature Distributions by Age Group (groups are not stacked)
</figcaption>
</figure>
</div>
</section>
<section id="preprocessing-steps" class="level3">
<h3 class="anchored" data-anchor-id="preprocessing-steps">Preprocessing Steps</h3>
<p>To prepare the data for analysis, we applied several cleaning and transformation steps:<br>
Column Renaming: Variable names were updated to be descriptive (e.g., ‘RIDAGEYR’ → ‘Age’) for clarity.<br>
Invalid Values: Observations with undocumented values in ‘physical_activity’ and ‘diabetic’ were removed to ensure consistency with the dataset’s metadata.<br>
One-Hot Encoding: Categorical variables (e.g., gender, physical_activity) were converted into binary indicators to enable their use in machine learning models.<br>
Standardization: Numeric variables (e.g., BMI, blood glucose) were standardized to ensure comparability across features with different scales.</p>
</section>
<section id="analytical-approach" class="level3">
<h3 class="anchored" data-anchor-id="analytical-approach">Analytical Approach</h3>
<p>We tested three models to classify respondents as adults or seniors based on health and nutrition data:<br>
Dummy Classifier: A baseline model predicting the majority class.<br>
Logistic Regression: Selected for its simplicity, interpretability, and alignment with healthcare applications.<br>
Support Vector Classifier (SVC): Included to explore the potential of non-linear relationships in improving classification.<br>
Performance was evaluated using metrics like precision, recall, F1-score, and AUC-PR, chosen for their ability to assess model performance in imbalanced datasets.</p>
<div class="cell" data-execution_count="4">
<div id="tbl-cv-dummy" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="4">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cv-dummy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Mean cross validation scores
</figcaption>
<div aria-describedby="tbl-cv-dummy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="4">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;"></th>
<th style="text-align: left;">Unnamed: 0</th>
<th style="text-align: right;">test_score</th>
<th style="text-align: right;">train_score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: left;">Dummy</td>
<td style="text-align: right;">0.847887</td>
<td style="text-align: right;">0.847887</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: left;">Logistic</td>
<td style="text-align: right;">0.696338</td>
<td style="text-align: right;">0.706056</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: left;">SVC</td>
<td style="text-align: right;">0.676056</td>
<td style="text-align: right;">0.703521</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="testing-best-model-on-test-data" class="level3">
<h3 class="anchored" data-anchor-id="testing-best-model-on-test-data">Testing Best Model on Test Data</h3>
<p>Since logistic regression had the best mean cross validation score, we selected it as our final model.</p>
<p>The model’s accuracy on test data was 0.725.</p>
</section>
<section id="tools" class="level3">
<h3 class="anchored" data-anchor-id="tools">Tools</h3>
<p>The following software packages were used in this project: <span class="citation" data-cites="Chorev_Deepchecks_A_Library_2022">Chorev et al. (<a href="#ref-Chorev_Deepchecks_A_Library_2022" role="doc-biblioref">2022</a>)</span>, <span class="citation" data-cites="2020NumPy-Array">Harris et al. (<a href="#ref-2020NumPy-Array" role="doc-biblioref">2020</a>)</span>, <span class="citation" data-cites="niels_bantilan-proc-scipy-2020">Bantilan (<a href="#ref-niels_bantilan-proc-scipy-2020" role="doc-biblioref">2020</a>)</span>, <span class="citation" data-cites="Pedregosa_Scikit-learn_Machine_Learning_2011">Pedregosa et al. (<a href="#ref-Pedregosa_Scikit-learn_Machine_Learning_2011" role="doc-biblioref">2011</a>)</span>, <span class="citation" data-cites="The_pandas_development_team_pandas-dev_pandas_Pandas">The pandas development team (<a href="#ref-The_pandas_development_team_pandas-dev_pandas_Pandas" role="doc-biblioref">n.d.</a>)</span>, <span class="citation" data-cites="VanderPlas2018">VanderPlas et al. (<a href="#ref-VanderPlas2018" role="doc-biblioref">2018</a>)</span>, <span class="citation" data-cites="python">Van Rossum and Drake (<a href="#ref-python" role="doc-biblioref">2024</a>)</span>.</p>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<p>The model’s precision score was 0.34, recall score was 0.645 and f1 score was 0.445.</p>
<section id="visualizing-model-performance" class="level3">
<h3 class="anchored" data-anchor-id="visualizing-model-performance">Visualizing model performance</h3>
<div id="fig-confusion-matrix" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-confusion-matrix-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../results/figures/Confusion_matrix.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-confusion-matrix-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Confusion matrix of the best model on test data
</figcaption>
</figure>
</div>
<p>The confusion matrix (<a href="#fig-confusion-matrix" class="quarto-xref">Figure&nbsp;2</a>) showed that while the model score is 0.725, it did very poorly at recall ( 0.645 ) and quite poorly at precision (0.34 ).</p>
<div id="fig-roc" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-roc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../results/figures/ROC.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-roc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: ROC curve of the best model on test data
</figcaption>
</figure>
</div>
<p>This performance was reflected in the ROC curve above (<a href="#fig-roc" class="quarto-xref">Figure&nbsp;3</a>). While it could differentiate the positive class “Senior” from the negative class to some extent, the model struggled to achieve both high true positive rates and low false positive rates. An AUC of 0.75 means that there is a 75% chance that a randomly chosen “Senior” will be ranked higher than a randomly chosen “Adult” by the model. In other words, the model is correctly distinguishing between “Senior” and “Adult” 75% of the time. With the AUC as 0.75, it means that 75% of the time, a randomly chosen “Senior” will have a higher predicted probability of being “Senior” than a randomly chosen “Adult”. This is a good indication that the model is better than random guessing, especially in distinguishing “Senior” from “Adult”.</p>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<section id="summary-of-findings" class="level3">
<h3 class="anchored" data-anchor-id="summary-of-findings">Summary of Findings:</h3>
<p>Our analysis sought to determine whether health and nutritional data could be used to predict whether individuals are adults (under 65) or seniors (65+). The results showed that age group prediction is feasible with moderate accuracy (~73.0%), but significant room for improvement remains. The initial high accuracy was largely due to class imbalance, with the model heavily favoring adults, the majority class. This highlighted the need for balanced metrics like F1 score to better evaluate the model’s performance.</p>
</section>
<section id="implications" class="level3">
<h3 class="anchored" data-anchor-id="implications">Implications:</h3>
<p>These findings indicate that predictive models can be a valuable tool for identifying age-related health patterns, which could inform public health strategies. However, the model’s current limitations—particularly its difficulty in identifying seniors—underscore the need for further refinement before it can be used in practice.</p>
</section>
<section id="recommendations" class="level3">
<h3 class="anchored" data-anchor-id="recommendations">Recommendations:</h3>
<ol type="1">
<li>Improving Data Handling: Address outliers in features like “physical_activity” and “diabetic” with deeper investigation rather than outright removal. Expand EDA to include pairwise correlations and feature importance analysis to reduce redundancy and engineer meaningful features.<br>
</li>
<li><strong>Model Enhancement:</strong> Incorporate hyperparameter tuning (e.g., tuning <code>C</code> in Logistic Regression) and use class weighting to address imbalance. Shift focus to metrics like precision, recall, and F1 score to ensure balanced performance.<br>
</li>
<li><strong>Alternative Modeling Approaches:</strong> Explore non-linear models, such as random forests, to capture potential interactions between health and nutritional factors that Logistic Regression may miss.<br>
</li>
<li><strong>Future Research:</strong> Investigate the most predictive health and nutritional factors for age classification. This could lead to actionable insights for tailoring public health programs to specific age groups.</li>
</ol>
</section>
<section id="limitations-and-future-work" class="level3">
<h3 class="anchored" data-anchor-id="limitations-and-future-work">Limitations and Future Work:</h3>
<p>The analysis faced several limitations, including oversimplified data cleaning and limited feature exploration during EDA. Logistic Regression, while interpretable, may not fully capture the complexity of age-related health patterns. Future work should focus on deeper feature analysis, advanced modeling techniques, hyper parameter tuning and incorporating a broader range of health and demographic variables.</p>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion:</h3>
<p>Data science is inherently iterative, and this analysis represents a step toward leveraging health data for age classification. By addressing the outlined limitations and exploring more advanced methods, we can better understand age-related health needs and design interventions that improve health outcomes for aging populations.</p>
</section>
</section>
<section id="references" class="level2">





</section>

<div class="quarto-listing quarto-listing-container-default" id="listing-listing">
<div class="list quarto-listing-default">
<div class="quarto-post image-right" data-index="0" data-categories="news,code,analysis" data-listing-date-sort="1736841600000" data-listing-file-modified-sort="1736890173617" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="1" data-listing-word-count-sort="7">
<div class="thumbnail">
<p><a href="./posts/post-with-code/index.html" class="no-external"></a></p><a href="./posts/post-with-code/index.html" class="no-external">
<p><img loading="lazy" src="./posts/post-with-code/image.jpg" class="thumbnail-image"></p>
</a><p><a href="./posts/post-with-code/index.html" class="no-external"></a></p>
</div>
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./posts/post-with-code/index.html" class="no-external">Post With Code</a>
</h3>
<div class="listing-subtitle">
<a href="./posts/post-with-code/index.html" class="no-external"></a>
</div>
<div class="listing-categories">
<div class="listing-category" onclick="window.quartoListingCategory('news'); return false;">
news
</div>
<div class="listing-category" onclick="window.quartoListingCategory('code'); return false;">
code
</div>
<div class="listing-category" onclick="window.quartoListingCategory('analysis'); return false;">
analysis
</div>
</div>
<div class="listing-description">
<a href="./posts/post-with-code/index.html" class="no-external">This is a post with executable code.</a>
</div>
</div>
<div class="metadata">
<a href="./posts/post-with-code/index.html" class="no-external">
<div class="listing-date">
Jan 14, 2025
</div>
<div class="listing-author">
Harlow Malloc
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="1" data-categories="news" data-listing-date-sort="1736582400000" data-listing-file-modified-sort="1736890173615" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="1" data-listing-word-count-sort="32">
<div class="thumbnail">
<p><a href="./posts/welcome/index.html" class="no-external"></a></p><a href="./posts/welcome/index.html" class="no-external">
<p class="card-img-top"><img src="posts/welcome/thumbnail.jpg"  class="thumbnail-image card-img"/></p>
</a><p><a href="./posts/welcome/index.html" class="no-external"></a></p>
</div>
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./posts/welcome/index.html" class="no-external">Welcome To My Blog</a>
</h3>
<div class="listing-subtitle">
<a href="./posts/welcome/index.html" class="no-external"></a>
</div>
<div class="listing-categories">
<div class="listing-category" onclick="window.quartoListingCategory('news'); return false;">
news
</div>
</div>
<div class="listing-description">
<a href="./posts/welcome/index.html" class="no-external">This is the first post in a Quarto blog. Welcome!</a>
</div>
</div>
<div class="metadata">
<a href="./posts/welcome/index.html" class="no-external">
<div class="listing-date">
Jan 11, 2025
</div>
<div class="listing-author">
Tristan O’Malley
</div>
</a>
</div>
</div>
</div>
<div class="listing-no-matching d-none">
No matching items
</div>
</div><div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-niels_bantilan-proc-scipy-2020" class="csl-entry" role="listitem">
Bantilan, Niels. 2020. <span>“Pandera: <span>S</span>tatistical <span>D</span>ata <span>V</span>alidation of <span>P</span>andas <span>D</span>ataframes.”</span> In <em><span>P</span>roceedings of the 19th <span>P</span>ython in <span>S</span>cience <span>C</span>onference</em>, edited by Meghann Agarwal, Chris Calloway, Dillon Niederhut, and David Shupe, 116–24. <a href="https://doi.org/ 10.25080/Majora-342d178e-010 ">https://doi.org/ 10.25080/Majora-342d178e-010 </a>.
</div>
<div id="ref-Chorev_Deepchecks_A_Library_2022" class="csl-entry" role="listitem">
Chorev, Shir, Philip Tannor, Dan Ben Israel, Noam Bressler, Itay Gabbay, Nir Hutnik, Jonatan Liberman, Matan Perlmutter, Yurii Romanyshyn, and Lior Rokach. 2022. <span>“<span class="nocase">Deepchecks: A Library for Testing and Validating Machine Learning Models and Data</span>.”</span> <em>Journal of Machine Learning Research</em> 23: 1–6. <a href="http://jmlr.org/papers/v23/22-0281.html">http://jmlr.org/papers/v23/22-0281.html</a>.
</div>
<div id="ref-DinhMiertschin2016" class="csl-entry" role="listitem">
Dinh, Andrew, and Susan Miertschin. 2016. <span>“A Data-Driven Approach to Predicting Diabetes and Cardiovascular Disease with Machine Learning.”</span> Semantic Scholar. <a href="https://www.semanticscholar.org/paper/A-data-driven-approach-to-predicting-diabetes-and-Dinh-Miertschin/01af1548ff1f3661d8bb813e8c35ee219a79ca9f">https://www.semanticscholar.org/paper/A-data-driven-approach-to-predicting-diabetes-and-Dinh-Miertschin/01af1548ff1f3661d8bb813e8c35ee219a79ca9f</a>.
</div>
<div id="ref-2020NumPy-Array" class="csl-entry" role="listitem">
Harris, Charles R., K. Jarrod Millman, Stéfan J van der Walt, Ralf Gommers, Pauli Virtanen, David Cournapeau, Eric Wieser, et al. 2020. <span>“Array Programming with <span>NumPy</span>.”</span> <em>Nature</em> 585: 357–62. <a href="https://doi.org/10.1038/s41586-020-2649-2">https://doi.org/10.1038/s41586-020-2649-2</a>.
</div>
<div id="ref-MukhtarAzwari2021" class="csl-entry" role="listitem">
Mukhtar, Hamid, and Sana Al Azwari. 2021. <span>“Investigating Non-Laboratory Variables to Predict Diabetic and Prediabetic Patients from Electronic Medical Records Using Machine Learning.”</span>
</div>
<div id="ref-NHANES2019" class="csl-entry" role="listitem">
NHANES. 2019. <span>“National Health and Nutrition Health Survey 2013-2014 (NHANES) Age Prediction Subset.”</span> UCI Machine Learning Repository.
</div>
<div id="ref-Papazafiropoulou2024" class="csl-entry" role="listitem">
Papazafiropoulou, Athanasia K. 2024. <span>“Diabetes Management in the Era of Artificial Intelligence.”</span> <em>Archives of Medical Sciences. Atherosclerotic Diseases</em> 9: e122–28.
</div>
<div id="ref-Pedregosa_Scikit-learn_Machine_Learning_2011" class="csl-entry" role="listitem">
Pedregosa, Fabian, Gaël Varoquaux, Alexandre Gramfort, Vincent Michel, Bertrand Thirion, Olivier Grisel, Mathieu Blondel, et al. 2011. <span>“<span class="nocase">Scikit-learn: Machine Learning in Python</span>.”</span> <em>Journal of Machine Learning Research</em> 12: 2825–30. <a href="https://jmlr.csail.mit.edu/papers/v12/pedregosa11a.html">https://jmlr.csail.mit.edu/papers/v12/pedregosa11a.html</a>.
</div>
<div id="ref-The_pandas_development_team_pandas-dev_pandas_Pandas" class="csl-entry" role="listitem">
The pandas development team. n.d. <span>“<span class="nocase">pandas-dev/pandas: Pandas</span>.”</span> <a href="https://doi.org/10.5281/zenodo.3509134">https://doi.org/10.5281/zenodo.3509134</a>.
</div>
<div id="ref-python" class="csl-entry" role="listitem">
Van Rossum, Guido, and Fred L. Drake. 2024. <span>“Python 3 Programming Language.”</span> <a href="https://www.python.org">https://www.python.org</a>.
</div>
<div id="ref-VanderPlas2018" class="csl-entry" role="listitem">
VanderPlas, Jacob, Brian Granger, Jeffrey Heer, Dominik Moritz, Kanit Wongsuphasawat, Arvind Satyanarayan, Eitan Lees, Ilia Timofeev, Ben Welsh, and Scott Sievert. 2018. <span>“Altair: Interactive Statistical Visualizations for Python.”</span> <em>Journal of Open Source Software</em> 3 (32): 1057. <a href="https://doi.org/10.21105/joss.01057">https://doi.org/10.21105/joss.01057</a>.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>